### ISSUE TITLE
ONVIF Network Interface not persistent

### ISSUE THREAD

**Issue by barrymossel** [roleoroleo/sonoff-hack#1]
When changing the ONVIF Network Interface via the web interface to Wireless, press save and refresh the page, it goes back to ethernet.

**Comment by roleoroleo** [comment]
It's a typo.
You can fix it changing ONVIF_INTERFACE with ONVIF_NETIF inside 2 files:

- /mnt/mmc/sonoff-hack/etc/system.conf
- /mnt/mmc/sonoff-hack/script/check_conf.sh

**Comment by barrymossel** [comment]
Cool will try it later. Unfortunately ONVIF seems (through ethernet) very slow though...

**Comment by roleoroleo** [comment]
What is slow?
ptz?

**Comment by barrymossel** [comment]
No, actually the stream is lagging 2-3 seconds (or even more). Big difference opposed to the Ewelink app (or RTSP stream from original firmware - at least it seems). Will test later.

**Comment by roleoroleo** [comment]
Onvif it's only a descriptor, doesn't provide stream.
The stream is the original rtsp produced from the cam through the sonoff firmware.

**Comment by barrymossel** [comment]
I already had that feeling lol. Just seemed that way then. App is way faster though.

But thanks for this hack. Really nice!

**Comment by roleoroleo** [comment]
Fixed in 0.0.5
https://github.com/roleoroleo/sonoff-hack/releases/tag/0.0.5
