### ISSUE TITLE
Feature request: Send snapshot via MQTT

### ISSUE THREAD

**Issue by fcsegalla** [roleoroleo/sonoff-hack#10]
It would be nice to send a snapshot or the short mp4 (as the ftp already does) via MQTT, not just the link, the file itself, this way we don't have to deal with firewall settings to send the image ou video to a monitoring app.

**Comment by roleoroleo** [comment]
Is there a "standard" protocol to do this?
jpg? png? base64 encoding?

**Comment by fcsegalla** [comment]
I got this ideia from this project: https://www.npmjs.com/package/ipcam2mqtt

I don't think there is a standard protocol for this but base64 seems a good solution

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/sonoff-hack/commit/4b4810b9fdedee2d9a67962d61370a2cd9a8853e

**Comment by fcsegalla** [comment]
Great news @roleoroleo
