### ISSUE TITLE
Possible Bug 0.0.6 - ewelink push messages on motion detection

### ISSUE THREAD

**Issue by fcsegalla** [roleoroleo/sonoff-hack#11]
I still receive push messages on motion detection from ewelink app even disabling the cloud support.

Is it a bug or am i doing something wrong?

**Comment by roleoroleo** [comment]
Does version 0.0.7 solve your issue?

**Comment by fcsegalla** [comment]
Hi, I just tested it. I turned on movement detection at ewelink app, disabled cloud, boot the camera.

Mqtt is working fine, cam appears as disconnected in the ewelink app but still receives push messages. 

Result: It didn't work
