### ISSUE TITLE
Feature request: Send PTZ commands via MQTT

### ISSUE THREAD

**Issue by fcsegalla** [roleoroleo/sonoff-hack#12]
This would be awesome

**Comment by roleoroleo** [comment]
Did you try http method?

**Comment by fcsegalla** [comment]
Yes, it worked fine, the problem with http method is that we have to deal with port forwarding in the client's router, with if can send PTZ commands and ask for a snapshot via MQTT we don't need to change the firewall at all

**Comment by rt400** [comment]
what the http method ? can you give example?

**Comment by roleoroleo** [comment]
@rt400 
Check the updated wiki.
There was an error.

**Comment by rt400** [comment]
@roleoroleo not working
i used with this url : http://192.168.1.101:8080/cgi-bin/preset.sh?action=go_preset&num=0&name=door
and i get This site can’t be reached

**Comment by roleoroleo** [comment]
I verified in the archive and the file is present.
Verified also in my cam and it's working.

**Comment by rt400** [comment]
@roleoroleo sorry..worng IP
