### ISSUE TITLE
Rotare PTZ setting when enable image rotation for ceiling mount.

### ISSUE THREAD

**Issue by kfulko** [roleoroleo/sonoff-hack#121]
When we enable camera rotation, PTZ works the other way around. While Home Assistant can be easily reversed, using other software is sometimes not possible.

**Comment by roleoroleo** [comment]
Which other software?

**Comment by kfulko** [comment]
Like Onvier on android TV

**Comment by roleoroleo** [comment]
Check this commit:
https://github.com/roleoroleo/sonoff-hack/commit/2c56fbc69ee92e0fd233d781897838fda488e006
