### ISSUE TITLE
How to connect to SSH?

### ISSUE THREAD

**Issue by korskantevin** [roleoroleo/sonoff-hack#127]
I'm using Putty. I got message "Server unexpectedly close network connection" every time i try to connect to CAM_!P, 22 port. Camera model is GK-200MP2С

**Comment by darkxst** [comment]
It should just be:
`ssh root@<IP>`
no password set by default.

**Comment by korskantevin** [comment]
> It should just be: `ssh root@<IP>` no password set by default.

thank you! putty from windows don't whan to connect any way. SSH client from my mikrotik router - error. But ssh from debian is ok
