### ISSUE TITLE
GK-200MP2-B New Firmware - not tested don't upgrade!

### ISSUE THREAD

**Issue by darkxst** [roleoroleo/sonoff-hack#128]
Looks like Sonoff is pushing a new firmware `V5520.2053.0504build20230103` out for the GK-200MP2-B . Dont upgrade to this, if you can help it. It hasnt been tested with Sonoff-hack just yet.

**Comment by vlaraort** [comment]
I can tell that I upgraded and rtsp is not working :( I can perform some tests if you want to try something

**Comment by Mr-P-Butthole** [comment]
I can't get it to work as my unit took new firmware before applying this overlay. I will make a separate issue once I rule out the sd-card and all other factors.

**Comment by XzaR90** [comment]
What is the progress of this? I got version 50520230320 looks like it is not working on that firmware.

**Comment by roleoroleo** [comment]
Sorry but I can't help with this issue.
I don't own this model.

**Comment by darkxst** [comment]
> I got version 50520230320

I have this build on one of my cameras and its working fine with Sonoff Hack. Probably best to open a new issue if you can't get it working. I am going to close this issue as its obsolete!
