### ISSUE TITLE
hostname broken on upgrade to 0.1.5

### ISSUE THREAD

**Issue by darkxst** [roleoroleo/sonoff-hack#135]
After upgrading to 0.1.5 hostname of the camera was `root` which is clearly incorrect. I am using the auto-generated hostname, and dont have an explicit hostname set in config.

For some reason, `/mnt/mmc/sonoff-hack/etc/hostname` was lost during upgrade and needed to be regenerated through the Web UI.

**Comment by roleoroleo** [comment]
If you crete it again, does it work after a reboot?

**Comment by darkxst** [comment]
Yeh once its recreated its fine and survives reboots.
and yes it was a web update.
