### ISSUE TITLE
ftppush.sh: uses rmdir but rmdir does not exist on S-CAM

### ISSUE THREAD

**Issue by couriersud** [roleoroleo/sonoff-hack#139]
ftppush (master) currently fails to remove empty folders. It uses `rmdir` which does not exist in the firmware.
Replacing `rmdir` with `rm -rf` works, but is more risky since rmdir would fail on non-empty folders.

**Comment by darkxst** [comment]
yes, but I hadnt tested it at all yet

**Comment by couriersud** [comment]
Once PR #141 is applied this issue can be closed.
