### ISSUE TITLE
Poor image quality

### ISSUE THREAD

**Issue by rt400** [roleoroleo/sonoff-hack#14]
Hi, First of all thanks for your work, wonderful work and I really enjoy it.
Now, recently I see that the quality that the camera survives is really poor and as if colorless. 
For example : 
![download](https://user-images.githubusercontent.com/38878996/95327050-2a2e3300-08ac-11eb-95e3-c19d9de58c23.jpeg)

Any idea why ??

**Comment by roleoroleo** [comment]
Sorry for the delay.
It seems uv components are inverted.
But I don't know how to solve because the snapshot is created from sonoff software.

**Comment by dehness** [comment]
Must be a design fault. One of my cameras does the exact same thing both when streaming via RTSP and when viewing in the Itead app. At first I thought it might be a bug with @roleoroleo's firmware but after removing the SDCard and doing a reset the problem remained so it's unaffected by this hack. Interestingly, the colours appear correctly when panning the camera (or moving it physically), but about a second after the movement stops, the colour problem comes back.

If you happen to find a fix for it, please let me know. 👍

**Comment by rt400** [comment]
@dehness same problem. also in ewelink app i got this color problem. i dont have and fix for that , its looks like a hardware issue.
