### ISSUE TITLE
Preset Preview Lost

### ISSUE THREAD

**Issue by StarMonkey1** [roleoroleo/sonoff-hack#147]
When you create a preset the camera preview (live view) on that page becomes broken and the live view cannot be displayed. There is just a broken image icon.

Before creating the preset the live view on that page works fine.

**Comment by roleoroleo** [comment]
Please, explain me better.

**Comment by StarMonkey1** [comment]
![image](https://github.com/roleoroleo/sonoff-hack/assets/104598361/434e14a7-9004-4111-814b-009a833d81e2)

**Comment by StarMonkey1** [comment]
This page works fine before creating a preset but stops working after I've created a preset.

**Comment by roleoroleo** [comment]
I tested it now and it seems working.
Which browser are you using?

**Comment by StarMonkey1** [comment]
Latest version of Chrome. This happens with two Sonoff cameras, I've formatted the cards and done a fresh install and still have the same problem.
