### ISSUE TITLE
Adjusting brightness and contrast 

### ISSUE THREAD

**Issue by androdlang** [roleoroleo/sonoff-hack#155]
Is there any way to adjust the basic functions of cameras sensor, such as brightness, contrast and saturation? In my case the camera(s) are in a very light environment and the picture is more ore less white...

**Comment by roleoroleo** [comment]
No sorry. It's not possible with my current knowledge.

**Comment by androdlang** [comment]
> No sorry. It's not possible with my current knowledge.

I'm not happy about missing this essential functionality, but anyway, thanks for reply!
