### ISSUE TITLE
FW available doesn't appears in maintenance page

### ISSUE THREAD

**Issue by Dim3333** [roleoroleo/sonoff-hack#162]
Hello,

For an unknown reason, since some weeks (i don't know exactly), the firmware available doesn't appears  in maintenance page. So, the upgrade firmware is not possible.
The fimware installed is displayed.

![Capture d'écran 2024-02-10 115157](https://github.com/roleoroleo/sonoff-hack/assets/43283756/263329e3-f7fc-45a9-804a-62e156bc31d3)

Firmware Version | 0.1.5
Base Version | V0525.1.276build20201103
Model | GK-200MP2C

**Comment by josecarre** [comment]
Same happens to me, stuck on 0.1.5
![image](https://github.com/roleoroleo/sonoff-hack/assets/10371413/1abf0abd-131c-4829-a8a3-9d6024d04e19)

**Comment by roleoroleo** [comment]
Yes, it's a known problem.
This is why I upgraded busybox to 1.36.1
To upgrade the hack use the manual procedure:
https://github.com/roleoroleo/sonoff-hack/wiki/Manual-firmware-upgrade

**Comment by Dim3333** [comment]
Thanks roleo.
It will be interesting for  a future release to integrate the possibility to upgrade firmawre (in maintenance page) by choosing a file and then update.

**Comment by roleoroleo** [comment]
> I read the procedure but I don't inderstand where copy the file GK-200MP2B_x.x.x.tgz on the camera SDCard.

In the root folder of the card,
No subfolders.

**Comment by Dim3333** [comment]
I done that before sent my last message and it doesn't works.

![Capture d'écran 2024-02-11 185107](https://github.com/roleoroleo/sonoff-hack/assets/43283756/a035b9ad-33db-46dd-acb8-0aeeb14123f8)

**Comment by roleoroleo** [comment]
Ignore the string.
Click the button.

**Comment by Dim3333** [comment]
I done.
![image](https://github.com/roleoroleo/sonoff-hack/assets/43283756/ae81832d-8242-4071-82b2-0ba0000630d8)

**Comment by roleoroleo** [comment]
If it doesn' work, backup your config and decompress the archive in your sd card (from your pc).
Just the sonoff-hack folder.
Then restore the config.

**Comment by josecarre** [comment]
> Yes, it's a known problem. This is why I upgraded busybox to 1.36.1 To upgrade the hack use the manual procedure: https://github.com/roleoroleo/sonoff-hack/wiki/Manual-firmware-upgrade

Thanks, I can confirm this method worked in GK-200MP2B and GK-200MP2-B.

**Comment by Dim3333** [comment]
> If it doesn' work, backup your config and decompress the archive in your sd card (from your pc). Just the sonoff-hack folder. Then restore the config.

It's works. Perfect.
