### ISSUE TITLE
Failing power supply?

### ISSUE THREAD

**Issue by wouterverduin** [roleoroleo/sonoff-hack#171]
Hi all! 

Been running my sonoff for about 3-4 months now. Running smooth however: i have already 3 failed power supplys?!
I use the one from sonoff that fits the camera although sold separatly. Are others running into this or just me? 
Could this be software related or just a weird hardware malfunction?

Thanks in advance!

**Comment by roleoroleo** [comment]
My power supply has been working fine for 4 years.
Maybe hw failure.
