### ISSUE TITLE
0.0.7 PTZ changes crash camera

### ISSUE THREAD

**Issue by EpicLPer** [roleoroleo/sonoff-hack#18]
Heya!

Just noticed that playing around too much on the PTZ page seems to easily crash the camera now. I've tried setting up a starting position and it seems that RTSP streaming and the PTZ snapshot streaming is too much for the cam to handle and it hangs, then reboots once the watchdog kicks in at some point.

**Comment by roleoroleo** [comment]
There are 2 know problems:
- https://github.com/roleoroleo/sonoff-hack/issues/5#issuecomment-699478071
- low memory: if you noticerandom reboots, try to enable swap file
