### ISSUE TITLE
Feature request: move to preset on boot

### ISSUE THREAD

**Issue by KhurramFHassan** [roleoroleo/sonoff-hack#2]
I just loaded this on my sonoff camera and like it very much. Its the best of both worlds: cloud and LAN. I would like to make a feature request: can the camera move to a predefined preset on boot?
Thanks

**Comment by roleoroleo** [comment]
I think I could add to the next release.

**Comment by KhurramFHassan** [comment]
Thanks

**Comment by roleoroleo** [comment]
Version 0.0.5
https://github.com/roleoroleo/sonoff-hack/releases/tag/0.0.5

**Comment by cjonhammar** [comment]
Not working in 0.0.5.
(thanks)

**Comment by roleoroleo** [comment]
Sorry, I forgot to commit some lines of code.
I was trying to change things too fast.
See 0.0.6.

**Comment by cjonhammar** [comment]
Nice! Works in 0.0.6
