### ISSUE TITLE
Feature request: TimeZone

### ISSUE THREAD

**Issue by dCypherNx** [roleoroleo/sonoff-hack#23]
I read the project files and found a prediction for the timezone parameter, but I saw that GMT0 is fixed, can you pass this parameter to the internal module?

**Comment by roleoroleo** [comment]
I didn't activate this parameter because it conflicts with the app setting.

**Comment by dCypherNx** [comment]
It's not perfect, but now I can change TZ for my location (I'm in São Paulo/Brazil, GMT-3, I should use America/Sao_Paulo, but I don't know why, maybe summer time, I had to use America/Buenos_Aires). The point is, it worked!
