### ISSUE TITLE
PTZ control via Zoneminder

### ISSUE THREAD

**Issue by nigelspowage** [roleoroleo/sonoff-hack#25]
Has anyone got PTZ controls working through Zoneminder ?

I saw the readme said to use ONVIF camera for Blue Iris so I attempted using the same for Zoneminder but with no luck.

**Comment by attilabalazsy** [comment]
I'm playing with the same, no luck yet

**Comment by attilabalazsy** [comment]
Yes, ONVIF Device Manager is able to control the PTZ. My issue with zoneminder is, that it is in a different subnet, so it does not finds the camera. This is what I need to solve first, then I can share more info here.

**Comment by roleoroleo** [comment]
If the cam is in a different subnet, wsdd discovery will not run successfully.
You need to input the ip address manually.

**Comment by roleoroleo** [comment]
Try this:
![immagine](https://user-images.githubusercontent.com/39277388/155502419-44659ef6-0b43-4e00-afa4-909943d5617c.png)

**Comment by attilabalazsy** [comment]
I've implemented the native PTZ control for zoneminder. If you are interested, I can share the control script.

**Comment by roleoroleo** [comment]
Yes, please.

**Comment by attilabalazsy** [comment]
Here is it (pls rename it to .pm)
[SonoffHack.pm.txt](https://github.com/roleoroleo/sonoff-hack/files/8193473/SonoffHack.pm.txt)

Installation details are in the description section of the script (at the bottom).
It is working from ZM UI (1.36.12) and also from ZM Ninja mobile app
I was not testing it very detailed and I'm also very new to ZM, so sorry for any mistakes. :)

**Comment by roleoroleo** [comment]
Thank you for sharing it.

**Comment by avg-I** [comment]
It would be great if @attilabalazsy 's script was integrated into zoneminder.
Have you considered submitted a PR there?
