### ISSUE TITLE
is there a way to switch off the IR leds?

### ISSUE THREAD

**Issue by sanderbrauns** [roleoroleo/sonoff-hack#26]
Hi,

The IR leds are automatically enabled and It would be great if we could switch them off manually.
The cam is behind a window, and with these dark days the IR leds switch on which blinds the camera.

Thanks!

**Comment by roleoroleo** [comment]
Probably there is a linux library with an api.
Like ptz management.
But I didn't study this option.

**Comment by adewilt8** [comment]
Are you still developing on this?

**Comment by roleoroleo** [comment]
Yes, but I didn't find a solution at the moment.

**Comment by illivanillie** [comment]
I am also interested 👍
