### ISSUE TITLE
PTZ via onvif?

### ISSUE THREAD

**Issue by illivanillie** [roleoroleo/sonoff-hack#34]
Hi, great stuff here! Love it!
Is there a way to integrate the PTZ commands or presets via onfiv (into home assistant).
I can't seem to find a was to control the cam. Only via the webpage.
Or is it just me?
Maybe you could help me :)

Thank you for your work!
Greetings from Germany

**Comment by roleoroleo** [comment]
Ptz should work with onvif.
Try it with odm.

**Comment by illivanillie** [comment]
Well i was trying to get it to work, was playing with the configuration etc., but I'm not able to. 
I don't know what you mean by odm.
In case you are familiar with home assistant: there are only two entities shown, the two streams.
I will try it with blue iris when i get my hands on a windows machine. 

greetings!

**Comment by roleoroleo** [comment]
I didn't try with ha, but i tried it with onvif device manager and it works.

**Comment by urbatecte** [comment]
Hi,
In HA it does not appear as an entity, but through servic `onvif.ptz`.
You need to give the entty n the servce data:
```
      service: onvif.ptz
      service_data:
        entity_id: camera.sonoff_camera_ch1
        movement: down
```

**Comment by illivanillie** [comment]
@urbatecte I just found out, before you commented. Thank you!
@roleoroleo love your stuff! Works great, truly amazing for a cheap cam.

Greetings!
