### ISSUE TITLE
Add OpenCV object tracking

### ISSUE THREAD

**Issue by JJSlabbert** [roleoroleo/sonoff-hack#35]
Tnx for the great work so far. I plan to add object tracking with opencv and python onvif. I will keep you up to date on it. If some one else did already do it, please share. Python onviff works great with this camera. See [](https://github.com/quatanium/python-onviv) and [](https://www.instructables.com/Sonoff-Camera-ONVIF-HACK/)

**Comment by zubus** [comment]
Any update on this? :)

**Comment by osos** [comment]
Have a look at this project: https://github.com/blakeblackshear/frigate
