### ISSUE TITLE
Timeout with ftpput

### ISSUE THREAD

**Issue by jimbovp** [roleoroleo/sonoff-hack#39]
Hi

Thanks a lot for this hack.
I am however unable to use the FTP upload feature properly. The directories are created on the FTP server, but no files are copied.
On server side I can see that the connection is established (on port 21), but no ftp-data connection is initiated (port 20). I suspect that the problem might be that the busybox ftpput on the IP cam is not working in passive mode, but I don't know how to change this.
On server side, all is configured correctly for passive mode (I can copy files through FTP from another client).
Any ideas or help?

Thanks
Jimbo

**Comment by roleoroleo** [comment]
Probably ftppush doesn't support passive mode and you can't change it.
Check if your server supports active mode.
