### ISSUE TITLE
PTZ Web interface control not working

### ISSUE THREAD

**Issue by JiMcNulty** [roleoroleo/sonoff-hack#49]
Using the latest version (0.1.0) with a fresh sonoff
Clicking the arrows does not do anything

**Comment by roleoroleo** [comment]
Which sonoff version?

**Comment by the-cobbler** [comment]
Firmware Version | 0.1.0
-- | --
Base Version | V2524.1.276build20201103
Model | GK-200MP2B



Now I see that the firmware didn't upgraded when I clicked it on the android app...not sure why it does not upgrade

**Comment by roleoroleo** [comment]
Actually your build is not tested.
I will check it.

**Comment by roleoroleo** [comment]
My cam didn't receive the update.
It's at V2524.1.245build20191030

**Comment by the-cobbler** [comment]
![image](https://user-images.githubusercontent.com/6442378/121938076-0e8cfd80-cd54-11eb-9202-86782c93484d.png)
It shows that the latest version is lower then the one I have, that's why it didn't "upgrade"

Its a brand new cam

**Comment by roleoroleo** [comment]
You probably have a fw version installed in factory and not released as over the air update.
Could you please create a backup?

**Comment by the-cobbler** [comment]
Sure, do you have a bash for that?

**Comment by roleoroleo** [comment]
```
dd if=/dev/mtd2 of=/mnt/mmc/mtd2.bin
dd if=/dev/mtd3 of=/mnt/mmc/mtd3.bin
dd if=/dev/mtd4 of=/mnt/mmc/mtd4.bin
```

**Comment by the-cobbler** [comment]
Already did :)
5 blocks
uploading

**Comment by the-cobbler** [comment]
Let me know if you need anything else

**Comment by roleoroleo** [comment]
Try this binary:
[ptz.gz](https://github.com/roleoroleo/sonoff-hack/files/6653407/ptz.gz)

**Comment by the-cobbler** [comment]
Works.
Thanks!
