### ISSUE TITLE
MJPEG server

### ISSUE THREAD

**Issue by JiMcNulty** [roleoroleo/sonoff-hack#50]
An MJPEG server could really help people that want to use this camera with Octoprint
Something like that:

https://github.com/eroji/rtsp2mjpg

It can replace the RTSP server if running together will consume too much resource

**Comment by roleoroleo** [comment]
The cam has no enough resources to convert h264 in mjpeg.
I already tried it.

**Comment by the-cobbler** [comment]
Tried this as well?

https://github.com/pikvm/ustreamer

It just feel like if you can take an 1080p screenshot, you can do a 3-4 of them a second
