### ISSUE TITLE
Camera port open unable to connect to web interface or SSH

### ISSUE THREAD

**Issue by willbrim** [roleoroleo/sonoff-hack#61]
Hi all I extracted the firmware using 7zip directly to the SD card, rebooted the camera with the card inserted, ran a port scan on the camera's IP address and see it is listening only on port 23 and 8080. I can not ssh or access the web interface. Has anyone else had this issue?

**Comment by willbrim** [comment]
I am trying to access the camera at its ip address via http://192.168.1.32:8080/

**Comment by willbrim** [comment]
Thanks I saw that it was updated to port 80 in the notes however,  I can not reach it on 80 and a port scan shows its listening on 8089 and 23 only. I am sure I grabbed the latest release also.

**Comment by willbrim** [comment]
![Screenshot_20210805-005103_Microsoft Remote Desktop](https://user-images.githubusercontent.com/39276631/128312724-a4ae44a2-9f35-4db1-8688-100986569f39.jpg)

**Comment by willbrim** [comment]
Here is an example from today running a test net con on the camera ip for all 3 ports. The camera shows up as unavailable in the ewelink app but I still get motion notifications somehow. I also did not set up wifi on it. I just have it plugged in directly via ethereal. Could that be an issue?

**Comment by roleoroleo** [comment]
Probably the hack is not running.
Check the sd card.

**Comment by willbrim** [comment]
Thanks for all the help I am not sure what I must be doing wrong here. I have the model B camera and downloaded the B version from the releases section 
![image](https://user-images.githubusercontent.com/39276631/130538624-39850260-827b-47fa-af9e-04e8c3b73455.png)
then sed 7-zip and selected extract files to 
![image](https://user-images.githubusercontent.com/39276631/130538751-860b3de7-0adc-49ad-b982-ac64c4b21ac0.png)
(E is the root letter of the SD card in my case).
Then it shows up as a tar file in the SD card:
![image](https://user-images.githubusercontent.com/39276631/130538816-d15f9dce-1dc0-478c-b1c9-9ba2fc900b55.png)
then plugged the camera back in and probed the IP address. Same results. It is listening on 8080 not 80 and not reachable via web at its ip address via http

**Comment by willbrim** [comment]
I was able to get the hack loaded! Thanks @roleoroleo !
