### ISSUE TITLE
no PTZ contol

### ISSUE THREAD

**Issue by gmcaesar** [roleoroleo/sonoff-hack#63]
no PTZ in HTTP config page or via ONVIF

Firmware Version | 0.1.1
Base Version | V0525.1.276build20201103
Model | GK-200MP2C

**Comment by gmcaesar** [comment]
thanks do i just add this bin to the sd card?

**Comment by roleoroleo** [comment]
You should copy it to the sonoff-hack/bin folder of your sd card.
Before copying, rename the old binary.
