### ISSUE TITLE
Video Path

### ISSUE THREAD

**Issue by rcsmota** [roleoroleo/sonoff-hack#74]
Hi.

My motion detection videos are being recorded in /mnt/mmc/plan_record/ but the videos shown on the camera's motion event page are pointing to /mnt/mmc/alarm_record/.

So I can only access it via FTP but not on the camera page.

![image](https://user-images.githubusercontent.com/31240306/144879910-3b58b610-d7a8-49bf-861b-965c00cbeef3.png)

The files has this format. nrc20211206070627.mp4

![image](https://user-images.githubusercontent.com/31240306/144880438-a7c9e4f7-142c-4d63-840e-b69fec9f0da2.png)

Thanks

**Comment by roleoroleo** [comment]
Probably they are in a different folder because are not generated by motion detection.

**Comment by rcsmota** [comment]
Hello @roleoroleo.

Not being motion detection what could it be? From the videos it appears to be motion detection?
Isn't it because you have turned on motion detection by the camera browser (supported in firmware 0.1.1) instead of by the eWeLink software?

**Comment by roleoroleo** [comment]
plan_record is used when you enable "Local record" with the app.
