### ISSUE TITLE
rtsp doesn't works

### ISSUE THREAD

**Issue by Dim3333** [roleoroleo/sonoff-hack#79]
Hi,

Firmware Version | 0.1.1
Base Version | V0525.1.276build20201103
Model | GK-200MP2C

Username and password are empty. I use this link:
[rtsp://hack:hack@MYIP/av_stream/ch0](url)

But connection refused with VLC (snapshot is ok). I don't know why ?

**Comment by sccsltd** [comment]
Is your port set to 554 for rtsp? One of mine was set to something different set it back and it was fine.

**Comment by Dim3333** [comment]
I used this link:
[rtsp://hack:hack@MYIP/av_stream/ch0](https://github.com/roleoroleo/sonoff-hack/issues/url)
and this one:
[rtsp://hack:hack@MYIP:554/av_stream/ch0](https://github.com/roleoroleo/sonoff-hack/issues/url)

Same issue.

**Comment by sccsltd** [comment]
http://CAM-IP/index.html?page=configurations

on that page you can check the ports or change them if you want to 👍😊

**Comment by Dim3333** [comment]
Yes, i do that.

**Comment by neurocis** [comment]
I am having the same issue but do not even see a listener on 554:

`[root@GK]# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:1000            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:http            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:7101            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:7103            0.0.0.0:*               LISTEN
tcp        0     64 172.27.1.129:ssh        172.27.1.141:57599      ESTABLISHED
`
I have tried changing ports for RTSP w/full resets to no avail. Stumped at this point. Thanks.
