### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by dCypherNx** [roleoroleo/sonoff-hack#8]
I turned onvif on and set hostname but when I try to connect from tinyCam(Android App) it says that there I must use hostname and it is unreacheable, even if I try to ping by name(Windows PC), there is something that I can do to solve this problem?

**Comment by roleoroleo** [comment]
Fixed in this commit:
https://github.com/roleoroleo/sonoff-hack/commit/6cb95d8b66fa3766c8552b19d842e66381cb5544

**Comment by dCypherNx** [comment]
Great !
