### ISSUE TITLE
MQTT (Mosquito Broker) under Home Assistant doesn't detect camera

### ISSUE THREAD

**Issue by Dim3333** [roleoroleo/sonoff-hack#80]
Hi,

Firmware Version | 0.1.1
Base Version | V0525.1.276build20201103
Model | GK-200MP2C

I enabled MQTT service but under Home Assistant the camera doesn't appears in the MQTT Broker.
I well checked IP, login and password. I don't know where is the issue.

Thanks.

**Comment by roleoroleo** [comment]
Open a mqtt client (like MQTT-Explorer), connect to the broker and check if you can see the topics configured in the cam.
![immagine](https://user-images.githubusercontent.com/39277388/154457429-bccb7556-7102-4cbc-a22e-110b36f3fd1e.png)

**Comment by roleoroleo** [comment]
Try to restart the cam while the broker is running and check again.

**Comment by Dim3333** [comment]
![image](https://user-images.githubusercontent.com/43283756/154522995-9ec2b2e8-8b93-4b85-8567-b60780ea61c7.png)

**Comment by roleoroleo** [comment]
Try this binary.
I fixed a bug when the alarms table is empty.
[mqtt-sonoff.gz](https://github.com/roleoroleo/sonoff-hack/files/8092029/mqtt-sonoff.gz)

**Comment by Dim3333** [comment]
It's seems better ....
![image](https://user-images.githubusercontent.com/43283756/154581845-5938cc2a-61e2-49a4-8dc5-d4356aba6f00.png)

But under Home Assistant the camera doesn't appears in the MQTT Broker.

**Comment by Dim3333** [comment]
I use MQTT (Mosquito Broker) provided by HA
![image](https://user-images.githubusercontent.com/43283756/154731226-aeece558-061c-4cf1-a9c0-39048241990f.png)

I already used your integration. Perfect +1
![image](https://user-images.githubusercontent.com/43283756/154731531-630c645c-2201-49fa-bd91-9863bbf44a2d.png)

So I can disabled MQTT service in cam parameters ?

**Comment by roleoroleo** [comment]
No, if you want to use my integration, mqtt is required.
But the cam does not appear in your mqtt broker because it doesn't use the discovery protocol.

**Comment by roleoroleo** [comment]
Discovery requires a special protocol to be implemented on the cam.
I didn't write it.

**Comment by darkxst** [comment]
Next release will have initial support for HA Discovery of the Camera Device info and the motion sensor and motion Image Sensor. 
It does not however implement all the features available in the Yi Hack integration.

**Comment by bigsem89** [comment]
I'm having trouble getting my camera to work with MQTT. It seems that the MQTT topic isn't being created. I've already verified the correctness of the user, login credentials, IP address, and even checked the camera's network connectivity.

**Comment by roleoroleo** [comment]
Please post your mqtt configuration (cam side).

**Comment by bigsem89** [comment]
> Please post your mqtt configuration (cam side).

Thank you for response.
i have managed to fix it by changing event location to 0, but now i've faced another issue:

#156
