### ISSUE TITLE
Rotate Flips and doesn't Rotate Image

### ISSUE THREAD

**Issue by StarMonkey1** [roleoroleo/sonoff-hack#86]
The rotate switch actually flips the image rather than rotates it.

This means cameras with ceiling mounts still show an upside down image even with Rotate Image enabled.

This has been an issue for a few releases and still exists in 0.1.2

**Comment by StarMonkey1** [comment]
Ok, so it seems it flips on the first reboot and rotates on the second reboot

**Comment by roleoroleo** [comment]
I think it's fixed here:
https://github.com/roleoroleo/sonoff-hack/commit/18bdd992451e0be75d48dfe5b7cead4c6d77d9e9
