### ISSUE TITLE
PTZ not working

### ISSUE THREAD

**Issue by WildRat** [roleoroleo/sonoff-hack#93]
Could you, please, help me solve missing PTZ problem? Other functions are working. I try swapping ptz bin - camera self calibrates, but PTZ controls did not work. 

Reported at webpage info:
Firmware Version	0.1.2
Base Version	V5520.2053.0402build20220712
Model	
Device ID	a63001b3fb
In eWelink app i see firmware name as GK-200MP2D

I can make fylesystem dumps if needed.

**Comment by roleoroleo** [comment]
Which control are you using to test PTZ?
onvif, web page, ...?

**Comment by WildRat** [comment]
ONVIF. Web page show message PTZ not supported.

**Comment by roleoroleo** [comment]
GK-200MP2D is not supported at the moment.
If you have a backup of the flash I could check if I can support it.

**Comment by WildRat** [comment]
Please take a look when you have time. Here ([backup.zip](https://github.com/roleoroleo/sonoff-hack/files/9376182/backup.zip)) are the files obtained through the script (_Dump your backup firmware (SD card)_). And this is a new version of the firmware that they sent with corrected time zones: [Time zone issue Fix package.zip](https://github.com/roleoroleo/sonoff-hack/files/9376123/Time.zone.issue.Fix.package.zip).

**Comment by roleoroleo** [comment]
Sorry but, after checking your backup, I found an error in the backup script at this page:
https://github.com/roleoroleo/sonoff-hack/wiki/Dump-your-backup-firmware-(SD-card))

Now, I updated it.
Please download it again and repeat the procedure.

**Comment by WildRat** [comment]
I made a dump using the new version of the script: [backup_new.zip](https://github.com/roleoroleo/sonoff-hack/files/9376313/backup_new.zip).

**Comment by roleoroleo** [comment]
Your cam is the same as in this post:
https://github.com/roleoroleo/sonoff-hack/issues/85

Sorry but I cannot support it, at the moment.

**Comment by WildRat** [comment]
I understand, thanks. Apparently this is a new version of this model. If there is an opportunity to work on this version, I can help check the functionality.

**Comment by roleoroleo** [comment]
To work on this version, we need to apply a lot of changes.
But a cam is needed.
And these changes must not break compatibility with the old version.
@puuu is working on it.

**Comment by ConorIA** [comment]
This should be fixed in 0.1.3.
https://github.com/roleoroleo/sonoff-hack/issues/85#issuecomment-1227500921

**Comment by WildRat** [comment]
But which version should I use?

**Comment by roleoroleo** [comment]
Based on the backup you shared with me, use GK-200MP2-B.

**Comment by roleoroleo** [comment]
@puuu @ConorIA 
Please reinstall 0.1.3 from scratch to avoid problem of future updates.

**Comment by WildRat** [comment]
It's working without errors, but VERY slow. Video frame in 3-5 seconds. PTZ controls reacts once in 30-70 seconds.

**Comment by roleoroleo** [comment]
Try ptz with the web service, not with the web page.
Because the web page calls a snapshot every second and the cam becomes slow.

**Comment by WildRat** [comment]
I tried with ONVIF Device Manager - PTZ works great! But no live video. And strange video presets:
![image](https://user-images.githubusercontent.com/1486048/186737182-ef60123a-5d3c-4820-84bc-430d9d10ed88.png)
![image](https://user-images.githubusercontent.com/1486048/186737192-54299067-fcf0-432c-a5ee-b08debe182f6.png)

**Comment by WildRat** [comment]
After couple reboots I managed to get it working with Synology Surveillance Station - video Ok, PTZ Ok. But strange video info:
![image](https://user-images.githubusercontent.com/1486048/186743089-2ac0b2a7-5711-4e7e-be64-aaa618334a0b.png)

**Comment by bigsem89** [comment]
The same thing with  GK-200MP2B.  PTZ doesn't work. I've tried PTZ on http page and also via onvif manager.
it works with ewelink.

Firmware Version | 0.1.3

Base Version | V2524.1.245build20191030
Model | GK-200MP2B
Device ID | a63000ffc4

**Comment by roleoroleo** [comment]
I will check it.

**Comment by bigsem89** [comment]
> I will check it.

Thanks 🙏

**Comment by roleoroleo** [comment]
Try to remove the file /mnt/mmc/sonoff-hack/bin/ptz
And reboot the cam.

**Comment by bigsem89** [comment]
> Try to remove the file /mnt/mmc/sonoff-hack/bin/ptz And reboot the cam.

did so. 
same result. ptz still doesn't work.

**Comment by roleoroleo** [comment]
Strange behavior.
Try to run the ws:
`http://IP_OF_YOUR_CAM/cgi-bin/ptz.sh?dir=right`

**Comment by bigsem89** [comment]
> Strange behavior. Try to run the ws: `http://IP_OF_YOUR_CAM/cgi-bin/ptz.sh?dir=right`

{
"error":"false"
}

**Comment by roleoroleo** [comment]
Does the cam moves?

**Comment by roleoroleo** [comment]
And check the error running ipc_cmd with a ssh console.

**Comment by bigsem89** [comment]
> Does the cam moves?

no

**Comment by bigsem89** [comment]
> And check the error running ipc_cmd with a ssh console.

What is ipc_cmd? where can i find it?

**Comment by roleoroleo** [comment]
Sorry, ipc_cmd is for another model. Try ptz command.
Login with ssh and run the following commands:
```
. /mnt/mmc/sonoff-hack/script/env.sh
ptz -a right
```

**Comment by roleoroleo** [comment]
Please, check if you have a library `libhardware.so` or `libptz.so` in the folder `/mnt/mtd/ipc/app/lib`

**Comment by officialjonot** [comment]
`[root@sonoff-c00d]# cd /mnt/mtd/ipc/app/lib
[root@sonoff-c00d]# ls
libNetLib.so            libdbmanager.so         libserviceinterface.so
libappmanager.so        libhardware.so          libservicemanager.so
libavcodec.so.55        libioport.so            libspeaker.so
libavformat.so.55       libled.so               libspi.so
libavsharemem.so        liblogmanager.so        libssl.so
libavutil.so.52         libmainic.so            libssl.so.1.0.0
libcfg.so               libportmap.so           libusermanager.so
libcommunication.so     libptz.so               libwdt.so
libcrypt-0.9.33.2.so    librtc.so               libwifi.so
libcrypt.so.0           librtmp.so              libz.so.1
libcrypto.so            libsd.so
libcrypto.so.1.0.0      libsensor.so`

**Comment by officialjonot** [comment]
```
[root@sonoff-c00d]# ptz_h -a right
ptz_h: can't resolve symbol 'hw_ptz_sendptz'
```

**Comment by roleoroleo** [comment]
Ok, copy the file:
`cp /mnt/mmc/sonoff-hack/bin/ptz_p /mnt/mmc/sonoff-hack/bin/ptz`

**Comment by officialjonot** [comment]
ok fantastic - its working on the web PTZ panel now (http://<IP-OF-CAMERA>/?page=ptz).  Iwill invesitgate to see if it works on ONVIF device manager. Thank you Roleo.

**Comment by EpicLPer** [comment]
> Ok, copy the file: `cp /mnt/mmc/sonoff-hack/bin/ptz_p /mnt/mmc/sonoff-hack/bin/ptz`

Just wanted to say that this also worked for mine :)
